name: Build Chocolatey Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      "api_key": ${{ secrets.CHOCO_API_KEY }}
      "gist_id": ${{ secrets.GIST_ID }}
      "gist_id_test": ${{ secrets.GIST_ID_TEST }}
      "github_user_repo": ${{ secrets.GH_USER_REPO }}
      "github_api_key": ${{ secrets.GH_API_KEY }}
      "au_Push": ${{ secrets.AU_PUSH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Chocolatey Profile
        run: |
          .\setup\chocoProfile.ps1

      - name: setup au
        run: |
          .\setup\au_setup.ps1

      - name: update and push all packages
        run: |
          .\update_all.ps1
