name: Build Chocolatey Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      "api_key": ${{ secrets.CHOCO_API_KEY }}
      "gist_id": ${{ secrets.GIST_ID }}
      "gist_id_test": ${{ secrets.GIST_ID_TEST }}
      "github_user_repo": ${{ secrets.GH_USER_REPO }}
      "github_api_key": ${{ secrets.GH_API_KEY }}
      "au_Push": ${{ secrets.AU_PUSH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Chocolatey Profile
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          $profileInstall = @'
          # Chocolatey profile
          $ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          if (Test-Path($ChocolateyProfile)) {
              Import-Module "$ChocolateyProfile"
          }
          '@
          $profileFile = "$profile"
          $chocoProfileSearch = '$ChocolateyProfile'
          if(Select-String -Path $profileFile -Pattern $chocoProfileSearch -Quiet -SimpleMatch) {
              Write-Debug "Chocolatey profile is already installed."
              return
          }
          $profileInstall | Out-File $profileFile -Append -Encoding (Get-FileEncoding $profileFile)

      - name: setup au
        run: |
          .\setup\au_setup.ps1

      - name: update and push all packages
        run: |
          .\update_all.ps1
